FROM ruby:2.7.2-alpine
RUN gem install bundler -v 2.1.4
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle config build.nokogiri --user-system-libraries
RUN bundle check || bundle install
COPY . ./
ENTRYPOINT [ "ruby", "question_access.rb" ]